<?php

use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
		    [
		        "name" => "Karachi", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "24.9056", 
		        "longitude" => "67.0822", 
		    ], 
		    [
		        "name" => "Lahore", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.549722", 
		        "longitude" => "74.343611", 
		    ], 
		    [
		        "name" => "Faisalabad", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.416667", 
		        "longitude" => "73.083333", 
		    ], 
		    [
		        "name" => "Serai", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.73933", 
		        "longitude" => "72.335655", 
		    ], 
		    [
		        "name" => "Rawalpindi", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.597331", 
		        "longitude" => "73.047904", 
		    ], 
		    [
		        "name" => "Multan", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.196789", 
		        "longitude" => "71.478241", 
		    ], 
		    [
		        "name" => "Gujranwala", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.155667", 
		        "longitude" => "74.187052", 
		    ], 
		    [
		        "name" => "Hyderabad City", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.396891", 
		        "longitude" => "68.377183", 
		    ], 
		    [
		        "name" => "Peshawar", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.008", 
		        "longitude" => "71.578488", 
		    ], 
		    [
		        "name" => "Abbottabad", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.1463", 
		        "longitude" => "73.211684", 
		    ], 
		    [
		        "name" => "Islamabad", 
		        "state" => "Islamabad", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.69", 
		        "longitude" => "73.0551", 
		    ], 
		    [
		        "name" => "Quetta", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.184138", 
		        "longitude" => "67.00141", 
		    ], 
		    [
		        "name" => "Bannu", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.985414", 
		        "longitude" => "70.602701", 
		    ], 
		    [
		        "name" => "Bahawalpur", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.4", 
		        "longitude" => "71.683333", 
		    ], 
		    [
		        "name" => "Sargodha", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.083611", 
		        "longitude" => "72.671111", 
		    ], 
		    [
		        "name" => "Sialkot City", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.499101", 
		        "longitude" => "74.52502", 
		    ], 
		    [
		        "name" => "Sukkur", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.705164", 
		        "longitude" => "68.857383", 
		    ], 
		    [
		        "name" => "Larkana", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.558985", 
		        "longitude" => "68.212035", 
		    ], 
		    [
		        "name" => "Sheikhupura", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.713056", 
		        "longitude" => "73.978333", 
		    ], 
		    [
		        "name" => "Mirpur Khas", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.5251", 
		        "longitude" => "69.0159", 
		    ], 
		    [
		        "name" => "Rahimyar Khan", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.419482", 
		        "longitude" => "70.302386", 
		    ], 
		    [
		        "name" => "Kohat", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.581958", 
		        "longitude" => "71.449291", 
		    ], 
		    [
		        "name" => "Jhang Sadr", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.269811", 
		        "longitude" => "72.316867", 
		    ], 
		    [
		        "name" => "Gujrat", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.574204", 
		        "longitude" => "74.075423", 
		    ], 
		    [
		        "name" => "Bardar", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.163737", 
		        "longitude" => "72.011571", 
		    ], 
		    [
		        "name" => "Kas\u016br", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.115556", 
		        "longitude" => "74.446667", 
		    ], 
		    [
		        "name" => "Dera Ghazi Khan", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.056142", 
		        "longitude" => "70.634766", 
		    ], 
		    [
		        "name" => "Masiwala", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.683333", 
		        "longitude" => "73.066667", 
		    ], 
		    [
		        "name" => "Nawabshah", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.248334", 
		        "longitude" => "68.409554", 
		    ], 
		    [
		        "name" => "Okara", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.808056", 
		        "longitude" => "73.445833", 
		    ], 
		    [
		        "name" => "Gilgit", 
		        "state" => "Gilgit-Baltistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.920007", 
		        "longitude" => "74.313656", 
		    ], 
		    [
		        "name" => "Chiniot", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.72", 
		        "longitude" => "72.978889", 
		    ], 
		    [
		        "name" => "Sadiqabad", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.30623", 
		        "longitude" => "70.130646", 
		    ], 
		    [
		        "name" => "Turbat", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.001224", 
		        "longitude" => "63.048491", 
		    ], 
		    [
		        "name" => "Dera Ismail Khan", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.832691", 
		        "longitude" => "70.902398", 
		    ], 
		    [
		        "name" => "Chaman", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.917689", 
		        "longitude" => "66.45259", 
		    ], 
		    [
		        "name" => "Zhob", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.340817", 
		        "longitude" => "69.449304", 
		    ], 
		    [
		        "name" => "Mehra", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.312817", 
		        "longitude" => "73.220525", 
		    ], 
		    [
		        "name" => "Parachinar", 
		        "state" => "Federally Administered Tribal Areas", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.895672", 
		        "longitude" => "70.098875", 
		    ], 
		    [
		        "name" => "Gwadar", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.12163", 
		        "longitude" => "62.325411", 
		    ], 
		    [
		        "name" => "Kundian", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.457747", 
		        "longitude" => "71.478918", 
		    ], 
		    [
		        "name" => "Shahdad Kot", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.847263", 
		        "longitude" => "67.906789", 
		    ], 
		    [
		        "name" => "Haripur", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.999967", 
		        "longitude" => "72.934093", 
		    ], 
		    [
		        "name" => "Matiari", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.59709", 
		        "longitude" => "68.4467", 
		    ], 
		    [
		        "name" => "Dera Allahyar", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.373529", 
		        "longitude" => "68.350778", 
		    ], 
		    [
		        "name" => "Lodhran", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.540507", 
		        "longitude" => "71.63357", 
		    ], 
		    [
		        "name" => "Batgram", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.679637", 
		        "longitude" => "73.026299", 
		    ], 
		    [
		        "name" => "Thatta", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "24.747449", 
		        "longitude" => "67.923528", 
		    ], 
		    [
		        "name" => "Bagh", 
		        "state" => "Azad Kashmir", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.981106", 
		        "longitude" => "73.776084", 
		    ], 
		    [
		        "name" => "Badin", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "24.655995", 
		        "longitude" => "68.836997", 
		    ], 
		    [
		        "name" => "Mansehra", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.330232", 
		        "longitude" => "73.196788", 
		    ], 
		    [
		        "name" => "Ziarat", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.382444", 
		        "longitude" => "67.725624", 
		    ], 
		    [
		        "name" => "Muzaffargarh", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.072576", 
		        "longitude" => "71.193788", 
		    ], 
		    [
		        "name" => "Tando Allahyar", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.462626", 
		        "longitude" => "68.719233", 
		    ], 
		    [
		        "name" => "Dera Murad Jamali", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.546568", 
		        "longitude" => "68.223081", 
		    ], 
		    [
		        "name" => "Karak", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.116334", 
		        "longitude" => "71.093536", 
		    ], 
		    [
		        "name" => "Mardan", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.197943", 
		        "longitude" => "72.04965", 
		    ], 
		    [
		        "name" => "Uthal", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.807222", 
		        "longitude" => "66.621944", 
		    ], 
		    [
		        "name" => "Nankana Sahib", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.4475", 
		        "longitude" => "73.697222", 
		    ], 
		    [
		        "name" => "Barkhan", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.897727", 
		        "longitude" => "69.525584", 
		    ], 
		    [
		        "name" => "Hafizabad", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.067857", 
		        "longitude" => "73.685449", 
		    ], 
		    [
		        "name" => "Kotli", 
		        "state" => "Azad Kashmir", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.518362", 
		        "longitude" => "73.902203", 
		    ], 
		    [
		        "name" => "Loralai", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.370512", 
		        "longitude" => "68.597949", 
		    ], 
		    [
		        "name" => "Dera Bugti", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.036188", 
		        "longitude" => "69.158493", 
		    ], 
		    [
		        "name" => "Jhang City", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.305684", 
		        "longitude" => "72.325941", 
		    ], 
		    [
		        "name" => "Sahiwal", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.666667", 
		        "longitude" => "73.1", 
		    ], 
		    [
		        "name" => "Sanghar", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.046558", 
		        "longitude" => "68.9481", 
		    ], 
		    [
		        "name" => "Pakpattan", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.341044", 
		        "longitude" => "73.386642", 
		    ], 
		    [
		        "name" => "Chakwal", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.933376", 
		        "longitude" => "72.858531", 
		    ], 
		    [
		        "name" => "Khushab", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.296667", 
		        "longitude" => "72.3525", 
		    ], 
		    [
		        "name" => "Ghotki", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.00604", 
		        "longitude" => "69.316077", 
		    ], 
		    [
		        "name" => "Kohlu", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.896505", 
		        "longitude" => "69.253235", 
		    ], 
		    [
		        "name" => "Khuzdar", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.738385", 
		        "longitude" => "66.643365", 
		    ], 
		    [
		        "name" => "Awaran", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.456768", 
		        "longitude" => "65.231436", 
		    ], 
		    [
		        "name" => "Nowshera", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.015828", 
		        "longitude" => "71.981232", 
		    ], 
		    [
		        "name" => "Charsadda", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.148221", 
		        "longitude" => "71.740604", 
		    ], 
		    [
		        "name" => "Qila Abdullah", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.728035", 
		        "longitude" => "66.661174", 
		    ], 
		    [
		        "name" => "Bahawalnagar", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.998659", 
		        "longitude" => "73.253604", 
		    ], 
		    [
		        "name" => "Dadu", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.730334", 
		        "longitude" => "67.776896", 
		    ], 
		    [
		        "name" => "Aliabad", 
		        "state" => "Gilgit-Baltistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "36.307028", 
		        "longitude" => "74.615449", 
		    ], 
		    [
		        "name" => "Lakki Marwat", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.607953", 
		        "longitude" => "70.911416", 
		    ], 
		    [
		        "name" => "Chilas", 
		        "state" => "Gilgit-Baltistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.412867", 
		        "longitude" => "74.104068", 
		    ], 
		    [
		        "name" => "Pishin", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.581762", 
		        "longitude" => "66.994061", 
		    ], 
		    [
		        "name" => "Tank", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.217071", 
		        "longitude" => "70.383154", 
		    ], 
		    [
		        "name" => "Chitral", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.851802", 
		        "longitude" => "71.786358", 
		    ], 
		    [
		        "name" => "Qila Saifullah", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.700766", 
		        "longitude" => "68.359843", 
		    ], 
		    [
		        "name" => "Shikarpur", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.957057", 
		        "longitude" => "68.637886", 
		    ], 
		    [
		        "name" => "Panjg\u016br", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.971861", 
		        "longitude" => "64.094594", 
		    ], 
		    [
		        "name" => "Mastung", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.799656", 
		        "longitude" => "66.845527", 
		    ], 
		    [
		        "name" => "Kalat", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.026629", 
		        "longitude" => "66.593607", 
		    ], 
		    [
		        "name" => "Gandava", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.613207", 
		        "longitude" => "67.485643", 
		    ], 
		    [
		        "name" => "Khanewal", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.301731", 
		        "longitude" => "71.932124", 
		    ], 
		    [
		        "name" => "Narowal", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.1", 
		        "longitude" => "74.883333", 
		    ], 
		    [
		        "name" => "Khairpur", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "27.529483", 
		        "longitude" => "68.761698", 
		    ], 
		    [
		        "name" => "Malakand", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.565609", 
		        "longitude" => "71.930432", 
		    ], 
		    [
		        "name" => "Vihari", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.033333", 
		        "longitude" => "72.35", 
		    ], 
		    [
		        "name" => "Saidu Sharif", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.746548", 
		        "longitude" => "72.355675", 
		    ], 
		    [
		        "name" => "Jhelum", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.934484", 
		        "longitude" => "73.731018", 
		    ], 
		    [
		        "name" => "Mandi Bahauddin", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.587037", 
		        "longitude" => "73.491231", 
		    ], 
		    [
		        "name" => "Bhakkar", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "31.625247", 
		        "longitude" => "71.06574", 
		    ], 
		    [
		        "name" => "Toba Tek Singh", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.974326", 
		        "longitude" => "72.482694", 
		    ], 
		    [
		        "name" => "Jamshoro", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.436078", 
		        "longitude" => "68.280172", 
		    ], 
		    [
		        "name" => "Kharan", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.584585", 
		        "longitude" => "65.415007", 
		    ], 
		    [
		        "name" => "Umarkot", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.36157", 
		        "longitude" => "69.736241", 
		    ], 
		    [
		        "name" => "Hangu", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.53198", 
		        "longitude" => "71.059499", 
		    ], 
		    [
		        "name" => "Timargara", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.826595", 
		        "longitude" => "71.844226", 
		    ], 
		    [
		        "name" => "Gakuch", 
		        "state" => "Gilgit-Baltistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "36.176826", 
		        "longitude" => "73.763834", 
		    ], 
		    [
		        "name" => "Jacobabad", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.281873", 
		        "longitude" => "68.437613", 
		    ], 
		    [
		        "name" => "Alp\u016brai", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.920577", 
		        "longitude" => "72.632556", 
		    ], 
		    [
		        "name" => "Mianwali", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "32.574095", 
		        "longitude" => "71.526386", 
		    ], 
		    [
		        "name" => "M\u016bsa Khel Bazar", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.859443", 
		        "longitude" => "69.82208", 
		    ], 
		    [
		        "name" => "Naushahro Firoz", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "26.840104", 
		        "longitude" => "68.122651", 
		    ], 
		    [
		        "name" => "New Mirpur", 
		        "state" => "Azad Kashmir", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.147815", 
		        "longitude" => "73.751867", 
		    ], 
		    [
		        "name" => "Daggar", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.511059", 
		        "longitude" => "72.484375", 
		    ], 
		    [
		        "name" => "Eidgah", 
		        "state" => "Gilgit-Baltistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.347115", 
		        "longitude" => "74.856317", 
		    ], 
		    [
		        "name" => "Sibi", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.542989", 
		        "longitude" => "67.87726", 
		    ], 
		    [
		        "name" => "Dalbandin", 
		        "state" => "Balochistan", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.888456", 
		        "longitude" => "64.406156", 
		    ], 
		    [
		        "name" => "Rajanpur", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "29.103513", 
		        "longitude" => "70.325038", 
		    ], 
		    [
		        "name" => "Leiah", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "30.961279", 
		        "longitude" => "70.939043", 
		    ], 
		    [
		        "name" => "Upper Dir", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.207398", 
		        "longitude" => "71.876801", 
		    ], 
		    [
		        "name" => "Tando Muhammad Khan", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "25.123007", 
		        "longitude" => "68.535773", 
		    ], 
		    [
		        "name" => "Attock City", 
		        "state" => "Punjab", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.76671", 
		        "longitude" => "72.359766", 
		    ], 
		    [
		        "name" => "Rawala Kot", 
		        "state" => "Azad Kashmir", 
		        "country_name" => "Pakistan", 
		        "latitude" => "33.857816", 
		        "longitude" => "73.760426", 
		    ], 
		    [
		        "name" => "Swabi", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.120181", 
		        "longitude" => "72.46982", 
		    ], 
		    [
		        "name" => "Kandhkot", 
		        "state" => "Sindh", 
		        "country_name" => "Pakistan", 
		        "latitude" => "28.243963", 
		        "longitude" => "69.182354", 
		    ], 
		    [
		        "name" => "Dasu", 
		        "state" => "Khyber Pakhtunkhwa", 
		        "country_name" => "Pakistan", 
		        "latitude" => "35.291687", 
		        "longitude" => "73.290602", 
		    ], 
		    [
		        "name" => "Athmuqam", 
		        "state" => "Azad Kashmir", 
		        "country_name" => "Pakistan", 
		        "latitude" => "34.571733", 
		        "longitude" => "73.897236", 
		    ]
		];
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('cities')->truncate();
		foreach ($cities as $key => $city_obj) {
			$city = new City();
			$city->name = $city_obj['name'];
			$city->country_name = $city_obj['country_name'];
			$city->state = $city_obj['state'];
			$city->latitude = $city_obj['latitude'];
			$city->longitude = $city_obj['longitude'];
			$city->save();
		}
		DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
