<?php
return [

    'students' => [
        'form_no' => [
            'title' => "Form No.",
            'data' => "form_no",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'admissions',
            'exportable' => true,
        ],
        'roll_no' => [
            'title' => "Roll No.",
            'data' => "roll_no",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'admission_date_formated' => [
            'title' => "Admission Date",
            'data' => "admission_date_formated",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'student_name' => [
            'title' => "Student Name",
            'data' => "student_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'father_name' => [
            'title' => "Father Name",
            'data' => "father_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'student_category' => [
            'title' => "Category",
            'data' => "student_category",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => false,
        ],
        'student_category_name' => [
            'title' => "Category",
            'data' => "student_category_name",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'session_name' => [
            'title' => "Session",
            'data' => "session_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'course_name' => [
            'title' => "Course",
            'data' => "course_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'affiliated_body_name' => [
            'title' => "Affiliated Body",
            'data' => "affiliated_body_name",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => false,
        ],
        'student_cnic_no' => [
            'title' => "Student CNIC",
            'data' => "student_cnic_no",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'father_cnic_no' => [
            'title' => "Father CNIC",
            'data' => "father_cnic_no",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'student_cell_no' => [
            'title' => "Student Cell No.",
            'data' => "student_cell_no",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'gender' => [
            'title' => "Gender",
            'data' => "gender",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'father_cell_no' => [
            'title' => "Father Cell No.",
            'data' => "father_cell_no",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'mother_cell_no' => [
            'title' => "Mother Cell No.",
            'data' => "mother_cell_no",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'brother_cell_no' => [
            'title' => "Brother Cell No.",
            'data' => "brother_cell_no",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'sister_cell_no' => [
            'title' => "Sister Cell No.",
            'data' => "sister_cell_no",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'guardian_cell_no' => [
            'title' => "Guardian Cell No.",
            'data' => "guardian_cell_no",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'other_cell_no' => [
            'title' => "Other Cell No.",
            'data' => "other_cell_no",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'present_address' => [
            'title' => "Present Address",
            'data' => "present_address",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'permanent_address' => [
            'title' => "Permanent Address",
            'data' => "permanent_address",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'd_o_b' => [
            'title' => "Date of Birth",
            'data' => "d_o_b",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'transport_status' => [
            'title' => "Transport Status",
            'data' => "transport_status",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'transport_stop' => [
            'title' => "Transport Stop",
            'data' => "transport_stop",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'file_module_number' => [
            'title' => "M - No.",
            'data' => "file_module_number",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'shift' => [
            'title' => "Shift",
            'data' => "shift",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'admission_date' => [
            'title' => "Admission Date",
            'data' => "admission_date",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'students',
            'exportable' => true,
        ],
        'total_package' => [
            'title' => "Total Receivable",
            'data' => "total_package",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'fee_packages',
            'exportable' => false,
        ],
        'total_payed' => [
            'title' => "Total Payed",
            'data' => "total_payed",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'fee_package_installments',
            'exportable' => false,
        ],
        'receivable_till_date' => [
            'title' => "Receivable Till Date",
            'data' => "receivable_till_date",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'fee_package_installments',
            'exportable' => false,
        ],
        'out_standing' => [
            'title' => "Outstanding",
            'data' => "out_standing",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'fee_package_installments',
            'exportable' => false,
        ],
        'options' => [
            'title' => "Actions",
            'data' => "options",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
    ],

    'enquiries' => [
        'previous_degree_body' => [
            'title' => "<input type='checkbox' onclick='checkall(this)' id='selectAllCheckbox'>",
            'data' => "previous_degree_body",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'id' => [
            'title' => "Sr.#",
            'data' => "id",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        
        'options' => [
            'title' => "Actions",
            'data' => "options",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'form_code' => [
            'title' => "Enq. ID",
            'data' => "form_code",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'enquiry_date' => [
            'title' => "Enq. Date",
            'data' => "enquiry_date",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        
        'enquiry_date_formated' => [
            'title' => "Enq. Date",
            'data' => "enquiry_date",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'enquiry_type' => [
            'title' => "Enq. Type",
            'data' => "enquiry_type",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'name' => [
            'title' => "Name",
            'data' => "name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'father_name' => [
            'title' => "Father Name",
            'data' => "father_name",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],

        'phone1' => [
            'title' => "Mobile 1",
            'data' => "phone1",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],

        'phone2' => [
            'title' => "Mobile 2",
            'data' => "phone2",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'landline' => [
            'title' => "Landline",
            'data' => "landline",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ], 
        'city' => [
            'title' => "City",
            'data' => "city_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'project_id' => [
            'title' => "Project",
            'data' => "project_name",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'product_id' => [
            'title' => "Product",
            'data' => "product_name",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'price_offer' => [
            'title' => "Price Offered",
            'data' => "price_offer",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ], 
        'enquiry_rank' => [
            'title' => "Cnic",
            'data' => "student_cnic_no",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'enquiry_status' => [
            'title' => "Enq. Status",
            'data' => "status",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'source_info_id' => [
            'title' => "Source of Info.",
            'data' => "source_info_id",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ], 
        'affiliated_body_id' => [
            'title' => "Affiliated Body",
            'data' => "affiliated_body_id",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'student_cnic_no' => [
            'title' => "Student CNIC",
            'data' => "student_cnic_no",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'area' => [
            'title' => "Area",
            'data' => "area",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'factory_name' => [
            'title' => "Factory Name",
            'data' => "factory_name",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiry_workers',
            'exportable' => true,
        ],
        'form_bypassed' => [
            'title' => "Form Bypassed",
            'data' => "form_bypassed",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
       'remarks' => [
            'title' => "Remarks",
            'data' => "remarks",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ], 
        'address' => [
            'title' => "Address",
            'data' => "address",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => false,
        ], 
    ],

    'enquiry_followups' => [
        'present_address' => [
            'title' => "<input type='checkbox' onclick='checkall(this)' id='selectAllCheckbox'>",
            'data' => "present_address",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'options' => [
            'title' => "Actions",
            'data' => "options",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiry_followups',
            'exportable' => false,
        ],
        'enq_form_code' => [
            'title' => "Enq. ID",
            'data' => "enq_form_code",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiry_followups',
            'exportable' => true,
        ],

        'next_date_formated' => [
            'title' => "Latest Followup Date",
            'data' => "next_date",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiry_followups',
            'exportable' => true,
        ],


        // 'next_date_formated' => [
        //     'title' => "Followup Date (Latest)",
        //     'data' => "next_date_formated",
        //     'visibility' => false,
        //     "searchable" => false,
        //     "table_name" => 'enquiry_followups',
        //     'exportable' => false,
        // ],

        'enquiry_type' => [
            'title' => "Enq. Type",
            'data' => "enquiry_type",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'name' => [
            'title' => "Name",
            'data' => "name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'phone1' => [
            'title' => "Mobile 1",
            'data' => "phone1",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'phone2' => [
            'title' => "Mobile 2",
            'data' => "phone2",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'landline' => [
            'title' => "Landline",
            'data' => "landline",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'city_name' => [
            'title' => "City",
            'data' => "city_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'academic_wing_id' => [
            'title' => "Project",
            'data' => "project_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'course_name' => [
            'title' => "Product",
            'data' => "product_name",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'revised_price' => [
            'title' => "Revised Price Offer",
            'data' => "revised_price",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiry_followups',
            'exportable' => true,
        ],


        // 'next_date_formated' => [
        //     'title' => "Followup Date (Latest)",
        //     'data' => "next_date_formated",
        //     'visibility' => false,
        //     "searchable" => false,
        //     "table_name" => 'enquiry_followups',
        //     'exportable' => false,
        // ],
        'enquiry_date' => [
            'title' => "Original Enq. Date",
            'data' => "enquiry_date",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],


        'father_name' => [
            'title' => "Father Name",
            'data' => "father_name",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],



        'phone_no' => [
            'title' => "Cell No.",
            'data' => "phone",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiry_contact_infos',
            'exportable' => false,
        ],
        // 'course_name' => [
        //     'title' => "Course",
        //     'data' => "course_name",
        //     'visibility' => false,
        //     "searchable" => false,
        //     "table_name" => 'enquiry_followups',
        //     'exportable' => false,
        // ],

        'enquiry_rank' => [
            'title' => "Enq. Ranking",
            'data' => "interest_level",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiry_followups',
            'exportable' => false,
        ],
        'enquiry_status' => [
            'title' => "Enq. Statuses",
            'data' => "status",
            'visibility' => true,
            "searchable" => false,
            "table_name" => 'enquiry_followups',
            'exportable' => false,
        ],
        'source_info_id' => [
            'title' => "Source of Info.",
            'data' => "source_info_id",
            'visibility' => true,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'session_name' => [
            'title' => "Session",
            'data' => "session_name",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'affiliated_body_id' => [
            'title' => "Affiliated Body",
            'data' => "affiliated_body_id",
            'visibility' => false,
            "searchable" => false,
            "table_name" => 'enquiries',
            'exportable' => false,
        ],
        'affiliated_body' => [
            'title' => "Developer",
            'data' => "affiliated_body_name",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'area' => [
            'title' => "Area",
            'data' => "area",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'previous_degree_name' => [
            'title' => "Previous Degree",
            'data' => "previous_degree_name",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'marks_obtained' => [
            'title' => "Marks Obtained",
            'data' => "marks_obtained",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
        'percentage' => [
            'title' => "Percentage",
            'data' => "percentage",
            'visibility' => false,
            "searchable" => true,
            "table_name" => 'enquiries',
            'exportable' => true,
        ],
       
    ],

];
